# Generated by Django 5.2.7 on 2025-11-09 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\+63\\d{10}$', 'Contact number must start with +63 and contain 13 characters total (e.g., +639123456789).')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_format',
            field=models.CharField(default='MM/DD/YYYY', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School'), ('CASE', 'College of Arts, Sciences, and Education (CASE)'), ('CHS', 'College of Health Sciences (CHS)'), ('CEAFA', 'College of Engineering, Fine Arts, and Architecture (CEAFA)'), ('CBMA', 'College of Business Management and Accountancy (CBMA)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,9}$', 'ID Number must contain only up to 9 digits.')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='number_format',
            field=models.CharField(default='1,000.00', max_length=10),
        ),
    ]
