# Generated by Django 5.2.7 on 2025-12-30 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userprofile_id_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
