# Generated by Django 5.2.7 on 2026-01-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
    ]
