# Generated by Django 5.2.7 on 2026-01-01 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
