# Generated by Django 5.2.7 on 2025-11-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic and Enrollment Concerns'), ('technical', 'Technical / Account Support'), ('facilities', 'Facilities and Maintenance'), ('lostfound', 'Lost and Found'), ('welfare', 'Student Welfare and Counselling')], max_length=50),
        ),
    ]
