# Generated by Django 5.2.7 on 2025-11-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_alter_ticket_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="ticket_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="urgency",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=10,
                null=True,
            ),
        ),
    ]
