# Generated by Django 5.2.7 on 2025-12-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticket_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic and Enrollment Concerns'), ('technical', 'Technical / Account Support'), ('facilities', 'Facilities and Maintenance'), ('lostfound', 'Lost and Found'), ('welfare', 'Student Welfare and Counselling'), ('generalinquiry', 'General Inquiry')], max_length=50),
        ),
    ]
