# Generated by Django 5.2.7 on 2026-01-10 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('updated', 'Updated'), ('status_change', 'Status Changed'), ('response', 'User Response'), ('deleted', 'Deleted')], default='updated', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
