# Generated by Django 5.2.7 on 2026-01-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_tickethistory_activity_type_tickethistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='deleted_ticket_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
