# Generated by Django 5.2.7 on 2026-03-19 00:31

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_tickethistory_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_history_attachments/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
