# Generated by Django 5.2.7 on 2026-03-19 11:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_tickethistory_attachment_alter_ticket_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
